config/routes.rb
Libros::Application.routes.draw do

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
  post '/client_auth', :to => "sessions#client_auth"

  resources :ads do

    collection do
      post "send_email"
    end

    resources :images
  end
  get '/search',:to => "ads#search"
  get '/' ,:to => "ads#search"
  get 'get_images', :to=> "ads#get_images"

  resources :categories

  resources :users
  get '/me' , :to=> "users#me"

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :description, :price, :title,:category_id
  belongs_to :user
  belongs_to :category
  has_many :images

  self.per_page = 20

  def Ad.search(query)

    return Ad.where("#{:title} LIKE '%#{query}%' OR #{:description} LIKE '%#{query}%'").order(:created_at.to_s << " DESC")

  end

  def image
    num_images = images.size
    if num_images > 0
      "/"+images.first.url
    else
      "http://placehold.it/400x400"
    end
  end

  def Ad.all
    order(:created_at.to_s << " DESC")
  end

  def Ad.get_latest_in_category(category_id, page)
    where("category_id=#{category_id}").order('created_at DESC').page(page)
  end

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.order('created_at DESC').page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ads }
    end
  end


  # GET /ads
  # GET /ads.json
  def search
    @categories = Category.get_top(4)
    if params[:query] and params[:query].size > 0 then
      @ads = Ad.search(params[:query])
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
    @ad = Ad.find(params[:id])
    @is_owner = @ad.user_id == session[:user_id]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad }
    end
  end

  def home

  end

  # GET /ads/new
  # GET /ads/new.json
  def new
    if session[:user_id]
      @ad = Ad.new
      @categories = Category.all
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @ad }
      end
    else
      send_to_fb_login
    end
  end

  # GET /ads/1/edit
  def edit
    if session[:user_id]

      @ad = Ad.find(params[:id])
      @topCategories = Category.all
    else
      send_to_fb_login
    end
  end

  # POST /ads
  # POST /ads.json
  def create
    if session[:user_id]
      @ad = Ad.new(params[:ad])
      if !@ad.image || @ad.image==""
        @ad.image = "http://placehold.it/400x400"
      end
      @ad.user_id=session[:user_id]
      @ad.category_id= params[:category]
      respond_to do |format|
        if @ad.save
          flash[:success]="Anuncio exitosamente creado"
          format.html { redirect_to @ad }
          format.json { render json: @ad, status: :created, location: @ad }
        else
          format.html { render action: "new" }
          format.json { render json: @ad.errors, status: :unprocessable_entity }


        end
      end
    else
      send_to_fb_login
    end
  end

  # PUT /ads/1
  # PUT /ads/1.json
  def update
    @ad = Ad.find(params[:id])

    if @ad.user_id==session[:user_id]
      respond_to do |format|
        if @ad.update_attributes(params[:ad])
          format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @ad.errors, status: :unprocessable_entity }
        end
      end
    else
      send_to_fb_login
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy

    @ad = Ad.find(params[:id])

    if @ad.user_id == session[:user_id]
      @ad.destroy

      respond_to do |format|
        format.html { redirect_to "/me" }
        format.json { head :no_content }
      end
    else
      send_to_fb_login
    end

  end


  def send_to_fb_login
    flash[:notice] = "Please log-in first"
    redirect_to "/"
  end

  def get_images

    @resp = BingAPI.get_images(params[:query],10)

    respond_to do |format|
      format.json {render json: @resp.body}
    end

  end

  def send_email
    message = params[:message]
    ad = Ad.find(params[:id])
    user_sender = User.find(session[:user_id])
    user_receiver = User.find(ad.user)
    UserMailer.send_email(user_sender, user_receiver,ad,message).deliver
    render text: "mensaje enviado exitosamente"
  end

end

app/helpers/ads_helper.rb
module AdsHelper

  def render_ad(ad, edit_button=false)
    render :partial => "ads/ad_thumbnail" ,:locals => {:ad=>ad, :edit_button=>edit_button}
  end




end

app/views/ads/_ad_thumbnail.html.erb
<% #TODO add paging support %>
<li>
  <div class="media">
    <a href="<%= ad_path(ad) %>">
      <%= image_tag ad.image ,:class=>"media-object pull-left thumbnail",:style => "max-height:100px; margin-right:5px" %>
    </a>
    <div class="media-body">
      <div class="pull-right">
        <%= render :partial => "ads/publicado_hace" , :locals => {:ad=>ad} %>
      </div>
      <h3 class="media-heading">
        <%= link_to ad.title, ad %>
      </h3>

      <p> <%= number_to_currency(ad.price) %> </p>
      <% if edit_button then %>
          <div class="btn-group pull-right">
            <%= link_to  ad,:confirm=>"Estas seguro que deseas remover tu anuncio?",:method=>:delete, :class=>"btn" do %>
                <i class="icon-trash"></i> remover
            <% end %>
            <%= link_to edit_ad_path(ad),:class=>"btn" do  %>
                <i class="icon-edit"></i> editar
            <% end %>
            <%= link_to new_ad_image_path(ad),:class=>"btn btn-success" do %>
                <i class="icon-camera"></i> agregar imagenes
            <%end %>
          </div>

      <% end %>
      <%= link_to ad.category do %>
        <p class="label label-info"> <%= ad.category.name %> </p>
      <% end %>
    </div>
  </div>
</li>

app/views/ads/_form.html.erb
<div class="row">
  <div class="span12">



    <%= form_for @ad,:html=>{:class=>"form-horizontal" } do |f| %>
        <% if @ad.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

              <ul>
                <% @ad.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>


        <div class="control-group">
          <%= f.label :title,"Titulo ",:class=>"control-label" %>
          <div class="controls">
            <%= f.text_field :title, :placeholder=>"ingresa un título",:class=>"input-xxlarge" %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :description, "Descripción" ,:class=>"control-label"%>
          <div class="controls">
            <%= f.text_area :description,:size=>"5x5",:placeholder=>"Agrega una corta descripcción para tu anuncio." %>
          </div>
        </div>
        <!--<div class="control-group">
          <%#= f.label :image,"Imagen",:class=>"control-label" %>
          <div class="controls">
            <%#= f.hidden_field :image %>
            <div id="loading-bar" class="progress progress-striped active input-large">
              <div class="bar" style="width: 100%;"></div>
            </div>
          </div>

          <div id="results"></div>
        </div>-->
        <div class="control-group">
          <%= f.label :price,"Precio",:class=>"control-label" %>
          <div class="controls">
            <%= f.text_field :price,:placeholder=>"Ej: '200000' o '50000 por clase'" %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :category,"Categoría" ,:class=>"control-label"%>
          <div class="controls">
            <%= select_tag :category, options_from_collection_for_select(@categories, "id", "name"), :multiple=>false  %>
          </div>
        </div>

        <!--<div class="control-group">
          <%#= label_tag :fb,"Publicar en mi wall de facebook",:class=>"control-label" %>
          <div class="controls">
            <%#= check_box_tag :fb, 0 %>
          </div>
        </div>-->

        <div class="control-group">
          <div class="controls">
            <%= f.submit "Publicar",:class=>"btn btn-primary" %>
          </div>
        </div>
    <% end %>

  </div>

</div>


<script>
    $('#loading-bar').hide();
    $('#ad_title').bind('change',function(){
        var data = {query: $('#ad_title').val() };
        $('#results').empty();
        $('#loading-bar').show();
        $.getJSON('/get_images', data, function(obj)
        {
            $('#loading-bar').hide();
            if (obj.d !== undefined)
            {
                $('#results').append(document.createElement('br'));
                var items = obj.d.results;
                for (var k = 0, len = items.length; k < len; k++)
                {
                    var item = items[k];
                    showImageResult(item);
                }
                $('.img-rounded').click(data,function(){
                    $('.img-rounded').removeClass('selected');
                    $(this).addClass('selected');
                    var src=$(this).attr('src');
                    $('#ad_image').val(src);
                });
            }
        });
    });



    // Shows one item of Image result.

    function showImageResult(item)
    {
        var a = document.createElement('a');
        a.href = item.MediaUrl;
        // Create an image element and set its source to the thumbnail.
        var i = document.createElement('img');
        i.src = item.Thumbnail.MediaUrl;
        // Make the object that the user clicks the thumbnail image.
        $(i).addClass("img-rounded");
        $(a).append(i);
        // Append the anchor tag and paragraph with the title to the results div.
        $('#results').append(i);
    }

    function updateStatus(){
        var status  =   document.getElementById('#ad_title').value;
        FB.api('/me/feed', 'post', { message: status }, function(response) {
            if (!response || response.error) {
                alert('Error occured');
            } else {
                alert('Status updated Successfully');
            }
        });
    }

</script>

app/views/ads/_publicado_hace.html.erb
<% days_ago = (Time.zone.now - ad.created_at ).to_i / 1.day %>
<% hours_ago = (Time.zone.now - ad.created_at ).to_i / 1.hour %>
<% minutes_ago = (Time.zone.now - ad.created_at ).to_i / 1.minute %>
<p class="muted">hace
    <% if minutes_ago == 0 %>
        un instante
    <% elsif hours_ago == 0 %>
        <%= pluralize(minutes_ago,"minuto","minutos") %>
    <% elsif days_ago == 0%>
        <%= pluralize(hours_ago,"hora","horas") %>
    <% else %>
        <%= pluralize(days_ago,"dia","dias") %>
    <% end %>
  por <%= link_to ad.user.name ,"http://facebook.com/#{ad.user.authorizations.first.uid}",:target=>"_blank" %>
</p>

app/views/ads/edit.html.erb
<%= render_header "Editar","Aquí puedes modificar tu anuncio", "icon-edit" %>
<div class="container">


  <div class="row">
    <div class="span12">



      <%= form_for @ad,:html=>{:class=>"form-horizontal" } do |f| %>
          <% if @ad.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

                <ul>
                  <% @ad.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>


          <div class="control-group">
            <%= f.label :title,"Titulo ",:class=>"control-label" %>
            <div class="controls">
              <%= f.text_field :title, :placeholder=>"ingresa un título",:class=>"input-xxlarge" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :description, "Descripción" ,:class=>"control-label"%>
            <div class="controls">
              <%= f.text_area :description,:size=>"5x5",:placeholder=>"Agrega una corta descripcción para tu anuncio." %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :price,"Precio",:class=>"control-label" %>
            <div class="controls">
              <%= f.text_field :price,:placeholder=>"Ej: '200000' o '50000 por clase'" %>
            </div>
          </div>


          <div class="control-group">
            <div class="controls">
              <%= f.submit "Guardar", :class=>"btn btn-primary" %>
            </div>
          </div>
      <% end %>

    </div>

  </div>

</div>

app/views/ads/home.html.erb
<div class="container">
  <div class="hero-unit">
    <div class="row" style="text-align: center;">
      <div class="span5" >
        <h1><i class="icon-time"></i></h1>
        <a class="btn btn-primary btn-large"> anuncios recientes</a>
      </div>
      <div class="span5">
        <h1><i class="icon-book"></i></h1>
        <a class="btn btn-primary btn-large"> publica un anuncio</a>
      </div>
    </div>
  </div>
</div>

app/views/ads/images.html.erb
<div class="container">
  <%= render_header "Agregar imagen","agregale imagenes a tu anuncio para que sea más atractivo" %>

</div>

app/views/ads/index.html.erb
<%= render_header "Anuncios recientes" , "mira los anuncios más recientes","icon-time" %>
<div class="container">
   <div class="row">
    <div class="span3">
      <%= render "categories/categories_widget" %>
    </div>
    <div class="span8">
      <ul class="nav nav-tabs nav-stacked ads-thumbnail">
          <% @ads.each do |ad| %>


              <%= render_ad ad %>

          <% end  %>
      </ul>
      <%= will_paginate @ads %>
    </div>
  </div>



</div>

app/views/ads/new.html.erb
<%= render_header "Publicar Anuncio",
                  "crea un anuncio descriptivo para lo que quieras vender o publicitar","icon-pencil" %>

<div class="container">

  <%= render 'form' %>

</div>

app/views/ads/search.html.erb
<div class="row hero-unit">

  <div class="container">
    <div class="span8 offset2 " id="search-panel">
      <%= form_tag "/search",:method=>"GET" , :class=> "search-box" do %>

          <h1>Busca un anuncio</h1>
          <p class="muted">Busca anuncios de libros, calculadoras, monitor&iacute;as, etc.</p>
          <div class="input-append">
            <%= text_field_tag :query, nil, :class=>"input-xxlarge",:placeholder=>"buscar"  %>
            <button id="search" class="btn btn-primary"> buscar!</button>
          </div>


      <% end %>

    </div>
  </div>

</div>

<div class="container">
  <% unless @ads %>
      <div class="row">
        <% @categories.each_with_index do |c,i| %>
            <% ad = c.ads.last %>
            <div class="span3">
              <div class="category-preview">
                <h4><%= link_to c.name, c %></h4>
                <%= image_tag ad.image %>
                <p>
                  <b><%= ad.title %></b>
                  <small><%= ad.description[0..50] << '...' %></small>
                </p>
                <%= link_to "más", c %>
              </div>
            </div>
        <% end %>
      </div>
  <% end %>
  <% if @ads%>
    <% if @ads.size == 0 %>
        <h2>Lo sentimos, no hemos encontrados resultados para "<span class="muted"><%= request.params[:query] %></span>"</h2>
        <h4>Tal vez querrías</h4>
          <ul>
            <li> ¿<%= link_to "Crear un anuncio", new_ad_path %>? </li>
            <li> ¿Preguntarle a tus amigos? </li>
          </ul>
    <% else %>
          <div class="row">
            <div class="offset1 span10" >
              <h4>Resultados para "<span class="muted"><%= request.params[:query] %></span>"</h4>

              <ul class="nav nav-tabs nav-stacked ads-thumbnail">
                <% @ads.each do |ad| %>
                    <%= render_ad ad %>
                <% end %>
              </ul>
            </div>
          </div>

          <script>

              $('.hero-unit').animate({ paddingTop: 10, paddingBottom:10},500);
              $(".search-box").animate({ marginTop: 10, marginBottom:10},500);

          </script>
    <% end %>
  <% else %>
      <fb:like href="http://clasificados.uniandes.edu.co" send="true"  show_faces="true"></fb:like>
      <%= render "layouts/footer" %>
  <% end %>


</div>

app/views/ads/show.html.erb
<% content_for :title, "Clasifiteca | "<<@ad.title %>

<div class="container">
  <br>
  <div class="row">

    <div class="span4">
      <div >
        <%= image_tag @ad.image,:class=> "center-image" %>
      </div>
      <% if @is_owner %>
          <%= link_to new_ad_image_path(@ad),:class=>"btn btn-success" do %>
              <i class="icon-camera"></i> agregar imagenes
          <%end %>
      <% end %>
      <% @ad.images.each_with_index do |i,index|  %>
          <a href="#modal_carousel" role="button" class="tiny-image-link" data-toggle="modal" onclick="$('.item:nth-child(<%=index+1%>)').attr('class','item active');">
            <%= image_tag "/#{i.url}" %>
          </a>
      <% end %>
    </div>
    <div class="span8">
      <h2><%= @ad.title %></h2>

      <p>
        <b>Descripción:</b>
        <%=  simple_format(@ad.description) %>
      </p>
      <%= render :partial => "ads/publicado_hace",:locals => {:ad => @ad} %>
      <span class="badge badge-warning"><%= number_to_currency(@ad.price) %></span>
      <p class="label label-info">
        <i class="icon-tag"></i><%= @ad.category.name %>
      </p>
      <br>
      <% if @is_owner == false && is_signed_in then %>
          <%= render_modal_link "contact_modal","btn btn-primary" do %>
              <i class="icon-envelope"></i> Contactar anunciante
          <% end %>
      <% end %>

      <%= render_modal "Contacto", "contact_modal" do %>
        <p>¿Estas interesado en el anuncio? Envíale un mensaje al dueño</p>

          <div class="input-append">
            <input class="span4" id="appendedInputButton" type="text">
            <button id="btnSend" class="btn" type="button" data-dismiss="modal">enviar</button>
          </div>

      <% end %>

    </div>
  </div>
  <hr>
  <!-- The facebook like widget -->
  <div class="row">
    <div class="span12">
      <%= render_standard_like("http://clasificados.uniandes.edu.co"<<ad_path(@ad)) %>
    </div>
  </div>
  <hr>
  <!-- The facebook comments widget -->
  <div class="row">
    <div class="span12" >
      <%= render_comments("http://clasificados.uniandes.edu.co"<<ad_path(@ad)) %>
    </div>
  </div>

</div>

<!-- The carousel inside a modal -->
<!-- Modal -->
<div id="modal_carousel" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
style="width:80%;margin-left: -40%;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Imágenes</h3>
  </div>
  <div class="modal-body" style="min-height: 300px">
    <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <% @ad.images.each_with_index do |img,index| %>
            <li data-target="#myCarousel" data-slide-to="<%= index %>" class="active"></li>
        <% end %>
      </ol>
      <!-- Carousel items -->
      <div class="carousel-inner">
        <% @ad.images.each do |i| %>
            <div class="item">
              <%= image_tag "/#{i.url}", :style=>'display: block;   margin-left: auto;   margin-right: auto;' %>
              <p><%= i.title %></p>
            </div>
        <% end %>
      </div>
      <!-- Carousel nav -->
      <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

<!-- The script that sends the e-mail -->
<script>

    $('#btnSend').click(function(){
        var text = $('#appendedInputButton').val();
        $.post("send_email",{message: text, id: <%=@ad.id %>}, function(res){
            alert(res);
        });
    });
</script>