config/routes.rb
Libros::Application.routes.draw do

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
  post '/client_auth', :to => "sessions#client_auth"

  resources :ads do

    collection do
      post "send_email"
    end

    resources :images
  end
  get '/search',:to => "ads#search"
  get '/' ,:to => "ads#search"
  get 'get_images', :to=> "ads#get_images"

  resources :categories

  resources :users
  get '/me' , :to=> "users#me"

end

app/views/layouts/_alerts.html.erb
<div style="margin-bottom: 0;">
  <% if flash[:notice] then %>
      <div class="alert">
        <%= flash[:notice]%>
        <a class="close" data-dismiss="alert" href="#">&times;</a>
      </div>
  <% end %>
  <% if flash[:success] then %>
      <div class="alert alert-success">
        <%= flash[:success]%>
        <a class="close" data-dismiss="alert" href="#">&times;</a>
      </div>
  <% end %>
  <% if flash[:error] then %>
      <div class="alert alert-error">
        <%= flash[:error]%>
        <a class="close" data-dismiss="alert" href="#">&times;</a>
      </div>
  <% end %>
</div>

app/views/layouts/_alt_footer.html.erb
<footer class="alt-footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h4><i class="icon-heart icon-large"></i>  &nbsp; &nbsp;Nuestros amigos</h4>

        <p><%= link_to "ACM - Uniandes", "http://acm.uniandes.edu.co/" ,:target=>"_blank" %> </p>
        <p><%= link_to "YouNoodle", "http://younoodle.com",:target=>"_blank" %> </p>
        <p><%= link_to "Sistemas - Uniandes", "http://sistemas.uniandes.edu.co",:target=>"_blank" %></p>
      </div>
      <div class="span4">
        <h4> <i class="icon-flag icon-large"></i>  &nbsp; &nbsp;Otros proyectos de ACM </h4>
        <p><%= link_to "HorarioLab", "http://horario.uniandes.edu.co",:target=>"_blank" %> </p>
        <p><%= link_to "StartupCriollo", "http://acm.uniandes.edu.co/startupcriollo",:target=>"_blank" %> </p>
        <p><%= link_to"ACM - página web", "http://acm.uniandes.edu.co/startupcriollo",:target=>"_blank" %></p>
      </div>
      <div class="span2">
        &nbsp;
      </div>
      <div class="span3">
        <h4> <i class="icon-thumbs-up icon-large"></i> &nbsp; &nbsp;Social Media</h4>
        <p>
          <%= link_to "http://facebook.com/ACMUniandes",:target=>"_blank" do %>
              <i class="icon-facebook-sign"></i> Facebook
          <% end %>
        </p>
        <p>
          <%= link_to "http://twitter.com/ACMUniandes",:target=>"_blank" do %>
              <i class="icon-twitter"></i> Twitter
          <% end %>
        </p>
        <p>
          <%= link_to "http://github.com/fernandohur/dmk" do %>
              <i class="icon-github-alt"></i> Github
          <% end %>
        </p>
      </div>

    </div>
    <div class="row">
      <div class="span4 alt-footer-copy">
        <p>
          <small> Usar Clasifiteca implica aceptar nuestros <a href="/terms">Terminos y Condiciones</a></small>
        </p>
        <p>
          <%= link_to "http://kopimi.com" do %>
              <%=  image_tag "kopimi.gif" %> Clasifiteca 2013
          <% end %>
        </p>

      </div>

    </div>
  </div>

</footer>

app/views/layouts/_fb_client_login.html.erb
<a href="#" onclick="fbLogin()">
  <i class="icon-facebook-sign"></i> login
</a>
<%= render_modal "Iniciando session","login" do %>
    <h2>Iniciando session</h2>
    <p>Por favor espera unos segundos</p>
<% end %>
<script>



</script>

app/views/layouts/_footer.html.erb
<div>
  <div class="row">
    <div class="span3">
      <h4>Qué es Clasifiteca</h4>
      <p>Clasifiteca es un lugar donde estudiantes pueden comprar y vender artículos que ya no utilicen como libros, batas, calculadoras, etc.</p>
    </div>
    <div class="span3">
      <h4>Quiénes somos</h4>
      <p>Clasifiteca es un proyecto de la <a href="http://acm.uniandes.edu.co" target="_blank">ACM-Uniandes</a>.
        Co-foundado por Carlos Duque y Fernando Hurtado, con la ayuda de Juan Sebastian Tejada
      y <a href="http://aneu.uniandes.edu.co" target="_blank" >ANEU</a></p>
    </div>
    <div class="span3">
      <h4>Contribuye</h4>
      <p>Si quieres contribuir con Clasifiteca envíanos un correo a
        acm@uniandes.edu.co con sujeto <b>Clasifiteca</b> y cuéntanos que te gustaría hacer. Siempre estamos abiertos a sugerencias</p>
    </div>

    <div class="span3">
      <h4>Contacto</h4>
      <p>Puedes contactarnos en: acm@uniandes.edu.co o a fernandohur@gmail.com</p>
    </div>
  </div>
  <div class="row">

  </div>
</div>

app/views/layouts/_header.html.erb
<div class="hero-unit" style="padding-top: 15px;padding-bottom: 10px;">

  <div class="container">
    <div class="row">
      <div class="span1">
        <i class="icon-3x <%= icon_name %>" style="vertical-align: bottom;"></i>
      </div>
      <div class="span11">
        <h2><%= title %> <small><%= subtitle %></small></h2>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<% user_id = get_user_id() %>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "/" , :class=>"brand" do %>
          Clasifi<span>Teca</span> <small style="font-size: 15px;"> beta </small>
      <% end %>
      <div class="nav-collapse collapse">

        <ul class="nav">
          <% if user_id then  %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-user"></i>
                  <%= User.find(user_id).name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "/me" do%>
                        <i class="icon-book"></i> mis anuncios
                    <%end%>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "/logout" do%>
                        <i class="icon-off"></i> logout
                    <%end%>
                  </li>
                </ul>
              </li>
          <% else %>
              <li>
                <%= render "layouts/fb_client_login" %>
              </li>
          <% end %>
          <%= render_if user_id do %>
              <li>
                <%= link_to new_ad_path do %>
                    <i class="icon-pencil"></i> publicar Anuncio
                <% end %>
              </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-tags"></i> categorías
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="nav-header">Top 5 Categorías</li>
              <% Category.get_top(5).each do |c| %>
                  <li> <%= link_to c.name, c %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "Todas",categories_path %></li>
            </ul>
          </li>
          <li>
            <%= link_to ads_path do %>
                <i class="icon-time"></i> anuncios recientes
            <% end %>
          </li>
        </ul>
        <form class="navbar-form pull-right nav-search">
  		<!--input type="text"></input-->
        </form>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <%h title = yield(:title) %>

  <title> <%= if title then title else "Clasifiteca | La comunidad Uniandina para intercambio de materiales universitarios" end  %> </title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta property="og:title" content="Clasifiteca | La comunidad Uniandina para intercambio de materiales universitarios"/>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render_fb_load_api %>
<%= render "layouts/navbar" %>

<div style="margin-top: 40px;">
  <%= render "layouts/alerts" %>
  <%= yield %>

</div>
<div>
  <%= render "layouts/alt_footer" %>
</div>
<%= render_uservoice %>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-39729680-1', 'uniandes.edu.co');
    ga('send', 'pageview');

</script>
</body>
</html>